# Generated by Django 4.1.5 on 2023-01-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=255, unique=True)),
                ('origin_url', models.TextField()),
                ('counter', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
